version: '3.8'

services:
  autoria-2024-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-autoria-nest}'
    volumes:
      - ./ autoria-2024-api-pg-db:/var/lib/postgresql/autoria-2024

  autoria-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

  autoria-2024-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./autoria-2024-api-s3-db:/usr/src/app/s3
    environment:
      MINIO_ROOT_USER: '${AWS_S3_ACCESS_KEY:-user}'
      MINIO_ROOT_PASSWORD: '${AWS_S3_SECRET_KEY:-password}'

volumes:
 autoria-2024-api-db:
 autoria-2024-api-s3: